version: '3.9'

services:
# TODO uncomment this after development of the main functionality:
#  web:
#    build: ./backend
#    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
#    volumes:
#      - ./backend:/code
#    ports:
#      - 8004:8000
#    env_file:
#      - .env

  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - .env