version: '3.9'

services:
  web:
    build: ./backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/code
    ports:
      - 8004:8000
    env_file:
      - .env
